version: "3.9"
services:
  order-service:
    container_name: order-service
    image: order-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend

networks:
  backend:
    external: true